# Generated by Django 3.2.5 on 2022-06-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vi_Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vi_Network_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('describtion', models.TextField()),
                ('image', models.ImageField(upload_to='vi_network')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vi_network.vi_network')),
            ],
        ),
    ]
