# Generated by Django 3.2.5 on 2022-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_network', '0002_vi_network_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vi_network_card',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='vi_network_card',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
