# Generated by Django 3.2.5 on 2022-06-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vi_network', '0003_auto_20220626_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='vi_network',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
