# Generated by Django 3.2.5 on 2022-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20220613_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='story_page',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='story_page',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='story_page',
            name='meta_title',
            field=models.TextField(default=''),
        ),
    ]
