# Generated by Django 3.2.5 on 2022-06-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20220613_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_link',
            field=models.URLField(default='#'),
        ),
    ]
