# Generated by Django 3.2.5 on 2022-06-30 14:43

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_page',
            name='paragraph',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
