# Generated by Django 3.2.5 on 2022-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=3, upload_to='blogs'),
            preserve_default=False,
        ),
    ]
