# Generated by Django 3.2.5 on 2022-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_newsletter_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='podcast',
            field=models.FileField(blank=True, null=True, upload_to='blogs/podcast'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogs/video'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
