# Generated by Django 3.2.5 on 2022-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20220607_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.TextField(default=''),
        ),
    ]
