# Generated by Django 3.2.5 on 2022-06-13 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
