# Generated by Django 3.2.5 on 2022-06-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blog_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
        migrations.AddField(
            model_name='blog',
            name='brief_youtube1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_youtube1',
            field=models.ImageField(blank=True, null=True, upload_to='othersvideoimage'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_youtube1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_link_youtube1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
