# Generated by Django 3.2.5 on 2022-06-26 06:45

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20220626_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
