# Generated by Django 3.2.5 on 2022-07-02 07:16

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_blog_page_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_page',
            old_name='heading',
            new_name='blog_heading',
        ),
        migrations.AddField(
            model_name='blog_page',
            name='paragraph',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog_page',
            name='top_heading',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
