# Generated by Django 3.2.5 on 2022-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_blog_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='podcast',
            field=models.TextField(blank=True, null=True),
        ),
    ]
