# Generated by Django 3.2.5 on 2022-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_services',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='other_services',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='others/videos'),
        ),
    ]
