# Generated by Django 3.2.5 on 2022-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0002_auto_20220616_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_services',
            name='yt_video_1',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='other_services',
            name='yt_video_2',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='other_services',
            name='yt_video_3',
            field=models.URLField(default='#'),
        ),
    ]
