# Generated by Django 3.2.5 on 2022-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0005_auto_20220616_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_services',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='others/sub_images'),
        ),
        migrations.AddField(
            model_name='other_services',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='others/sub_images'),
        ),
        migrations.AddField(
            model_name='other_services',
            name='sub_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='others/sub_images'),
        ),
        migrations.AddField(
            model_name='other_services',
            name='sub_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='others/sub_images'),
        ),
    ]
