# Generated by Django 3.2.5 on 2022-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0006_auto_20220623_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_services',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='other_services',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='other_services',
            name='meta_title',
            field=models.TextField(default=''),
        ),
    ]
