# Generated by Django 3.2.5 on 2022-06-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0007_auto_20220623_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_services',
            name='secondary_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
