# Generated by Django 3.2.5 on 2022-06-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0008_other_services_secondary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_services_external_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='others/external_images')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='other_services',
            name='inner_image',
            field=models.ImageField(blank=True, null=True, upload_to='others/inner_images'),
        ),
        migrations.CreateModel(
            name='other_services_blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.CharField(max_length=200)),
                ('other_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_services.other_services')),
            ],
        ),
    ]
