# Generated by Django 3.2.5 on 2022-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0009_auto_20220625_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_services',
            name='block_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_services_blocks',
            name='paragraph',
            field=models.TextField(max_length=200),
        ),
    ]
