# Generated by Django 3.2.5 on 2022-06-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0012_alter_other_services_inner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_services',
            name='secondary_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_services_blocks',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
