# Generated by Django 3.2.5 on 2022-06-26 06:45

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0013_auto_20220626_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_services',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
