# Generated by Django 3.2.5 on 2022-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0014_alter_other_services_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='other_services_external_link',
        ),
        migrations.AddField(
            model_name='other_services',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other_services',
            name='serial_number',
            field=models.IntegerField(default=0),
        ),
    ]
