# Generated by Django 3.2.5 on 2022-06-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0015_auto_20220626_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_services',
            name='slug',
            field=models.SlugField(),
        ),
    ]
