# Generated by Django 3.2.5 on 2022-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0027_auto_20220611_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(),
        ),
    ]
