# Generated by Django 3.2.5 on 2022-06-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0028_auto_20220611_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='keywords',
            new_name='meta_keywords',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='meta_title',
        ),
    ]
