# Generated by Django 3.2.5 on 2022-06-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0025_delete_metatags'),
        ('home', '0055_metatags'),
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.TextField()),
                ('subtitle_mobile', models.TextField()),
                ('title2', models.CharField(blank=True, default='JOIN US TO FOLLOW YOUR PASSION', max_length=100, null=True)),
                ('description', models.TextField()),
                ('form_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='career_table_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='metatags',
            name='categories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='metatags',
            name='subcategories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategories'),
        ),
        migrations.CreateModel(
            name='career_header_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.career_table_header')),
            ],
        ),
    ]
