# Generated by Django 3.2.5 on 2022-06-10 07:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_two_four_seven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_four_seven',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
