# Generated by Django 3.2.5 on 2022-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_two_four_seven_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two_Four_Seven_Integrated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='24x7/integrated')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Two_Four_Seven_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='two_four_seven',
            name='body',
            field=models.TextField(),
        ),
    ]
