# Generated by Django 3.2.5 on 2022-06-11 05:36

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_academic_page_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
