# Generated by Django 3.2.5 on 2022-06-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_alter_academics_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Sub_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=254)),
                ('meta_description', models.TextField()),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subcategories')),
            ],
        ),
    ]
