# Generated by Django 3.2.5 on 2022-06-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_meta_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_sub_categories',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meta_sub_categories',
            name='meta_name',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='meta_sub_categories',
            name='sub_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.subcategories'),
        ),
    ]
