# Generated by Django 3.2.5 on 2022-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20220611_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('meta_keywords', models.TextField(default='')),
                ('meta_description', models.TextField(default='')),
                ('meta_title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='other_services_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('meta_keywords', models.TextField(default='')),
                ('meta_description', models.TextField(default='')),
                ('meta_title', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='academic_page',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='academic_page',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='academic_page',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='career',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='career',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='career',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='career',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='career'),
        ),
        migrations.AddField(
            model_name='marketing_page',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='marketing_page',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='marketing_page',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shorts_page',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shorts_page',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shorts_page',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='two_four_seven_page',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='two_four_seven_page',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='two_four_seven_page',
            name='meta_title',
            field=models.TextField(default=''),
        ),
    ]
