# Generated by Django 3.2.5 on 2022-06-13 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20220613_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorts',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
