# Generated by Django 3.2.5 on 2022-06-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_shorts_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='other_services',
        ),
        migrations.DeleteModel(
            name='other_services_page',
        ),
    ]
