# Generated by Django 3.2.5 on 2022-06-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20220615_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='keywords',
            new_name='meta_keywords',
        ),
        migrations.RenameField(
            model_name='subcategories',
            old_name='title',
            new_name='meta_title',
        ),
    ]
