# Generated by Django 3.2.5 on 2022-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_video_marketing_video_marketing_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.TextField(default='')),
                ('meta_description', models.TextField(default='')),
                ('meta_title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_keywords', models.TextField(default='')),
                ('meta_description', models.TextField(default='')),
                ('meta_title', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='aboutus',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='creators',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='creators',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='creators',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='work',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='work',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='work',
            name='meta_title',
            field=models.TextField(default=''),
        ),
    ]
