# Generated by Django 3.2.5 on 2022-06-30 14:43

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_shorts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
