# Generated by Django 3.2.5 on 2022-07-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20220630_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_table_header',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
