# Generated by Django 3.2.5 on 2022-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_career_table_header_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='two_four_seven_page',
            name='sub_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='24x7/sub_images'),
        ),
        migrations.AddField(
            model_name='two_four_seven_page',
            name='sub_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='24x7/sub_images'),
        ),
        migrations.AddField(
            model_name='two_four_seven_page',
            name='sub_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='24x7/sub_images'),
        ),
        migrations.AddField(
            model_name='two_four_seven_page',
            name='sub_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='24x7/sub_images'),
        ),
    ]
