# Generated by Django 3.2.5 on 2022-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20220702_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_work_youtube_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('brief', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='work_videos')),
                ('video_link', models.CharField(max_length=100)),
            ],
        ),
    ]
