# Generated by Django 3.2.5 on 2022-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_category',
            name='desciption',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
