# Generated by Django 3.2.5 on 2022-06-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0002_super_category_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_category',
            old_name='desciption',
            new_name='description',
        ),
    ]
