# Generated by Django 3.2.5 on 2022-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='participation',
            field=models.IntegerField(default=1),
        ),
    ]
