# Generated by Django 3.2.5 on 2022-06-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0005_alter_sub_category_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d2c_page',
            name='short_description1',
        ),
        migrations.RemoveField(
            model_name='d2c_page',
            name='short_description2',
        ),
        migrations.RemoveField(
            model_name='d2c_page',
            name='short_description3',
        ),
        migrations.RemoveField(
            model_name='d2c_page',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='d2c_page',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='d2c_page',
            name='title3',
        ),
        migrations.AddField(
            model_name='d2c_page',
            name='short_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='d2c_page',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='D2C_Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='d2c')),
                ('d2c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dare2creative.d2c_page')),
            ],
        ),
    ]
