# Generated by Django 3.2.5 on 2022-06-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0007_auto_20220615_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='feautred',
            new_name='isFeautered',
        ),
    ]
