# Generated by Django 3.2.5 on 2022-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0008_rename_feautred_sub_category_isfeautered'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='d2c_posters',
            name='url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='eligibility',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_category',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='meta_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='register_url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(default='', editable=False),
            preserve_default=False,
        ),
    ]
