# Generated by Django 3.2.5 on 2022-06-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0009_auto_20220615_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dare2creative.super_category'),
        ),
        migrations.AlterField(
            model_name='d2c_posters',
            name='d2c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dare2creative.d2c_page'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dare2creative.category'),
        ),
    ]
