# Generated by Django 3.2.5 on 2022-06-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2creative', '0010_auto_20220615_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='eligibility',
            field=models.TextField(),
        ),
    ]
